# Generated by Django 5.1 on 2024-10-01 16:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('password', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='image.jpg')),
                ('unique_id', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('user_status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TicketsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ticket_status', models.CharField(choices=[('open', 'open'), ('close', 'close'), ('in_progress', 'in_progress')], default='open', max_length=20)),
                ('ticket_mode', models.CharField(choices=[('urgent', 'urgent'), ('low', 'low'), ('medium', 'medium')], default='low', max_length=20)),
                ('ticket_title', models.TextField(blank=True, max_length=250, null=True)),
                ('ticket_description', models.TextField(blank=True, max_length=250, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='Tickets.user')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created'],
            },
        ),
    ]
